version: '3.7'
services:
  nlu:
    build: ./
    volumes:
      - ./config.yml:/app/config.yml
      - ./models/:/app/models/
    ports:
      - "8080:8080"
    networks:
      - test-network
networks:
  test-network:
